# Generated by Django 3.2.3 on 2021-05-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('thumbnails', models.URLField()),
                ('description', models.TextField()),
                ('pub_date', models.CharField(max_length=25)),
            ],
        ),
    ]
